name: Update Spotify Counter

on:
  workflow_dispatch:

jobs:
  update-counter:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Clone private repo
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/wonytest0-dev/spotify-counter-private.git

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: spotify-counter-private
        run: npm install

      - name: Install Playwright
        working-directory: spotify-counter-private
        run: npx playwright install chromium --with-deps

      - name: Restore Spotify Login
        run: |
          cat << 'EOF' > spotify-counter-private/spotify-login.json
          ${{ secrets.SPOTIFY_LOGIN_JSON }}
          EOF

      - name: Run Counter
        working-directory: spotify-counter-private
        run: node generate-counter.js

      - name: Copy generated files
        run: |
          cp spotify-counter-private/counter.json .
          cp spotify-counter-private/spotify-snapshot.json .
          cp spotify-counter-private/spotify-history.json .

      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add counter.json
          git add spotify-snapshot.json
          git add spotify-history.json

          git diff --staged --quiet || git commit -m "update spotify counter"

          git push
